### ISSUE TITLE
What are the contents in env file?

### ISSUE THREAD

**Issue by Jordaar** [Controlfreak707/RoboLiam#22]
Help needed....

Can I know the contents in the env file?

**Comment by Controlfreak707** [comment]
Obviously I can't tell you any of the definitions but the variable names are as follows:
```
BOT_TOKEN
FIREBASE_CLIENT_EMAIL
FIREBASE_PRIVATE_KEY
GIPHY_KEY
GOOGLE_KEY
RAPIDAPI_KEY
```
