### ISSUE TITLE
[Issue] [Question] [All the flairs] Where do I put the token?

### ISSUE THREAD

**Issue by Dragonizedpizza** [Controlfreak707/RoboLiam#40]
I'm not sure where to put the bot token... I have super smol brain so uh...

- [x] I'm dumb.
- [x] I have super smol brain.

**Comment by Controlfreak707** [comment]
Don't worry about it, I get asked this all the time! The bot token (and other private keys and what-not) are stored in a file named exactly `.env` (you will have to create this file). The format of the file is as follows:
```.env
BOT_TOKEN=token goes here
OTHER_VAR=some value
```

**Comment by Dragonizedpizza** [comment]
ty
